"""empty message

Revision ID: 1c13336cda69
Revises: 
Create Date: 2022-09-02 16:27:24.877018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c13336cda69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments_times',
    sa.Column('deprtment_id', sa.Integer(), nullable=False),
    sa.Column('from', sa.Time(), nullable=False),
    sa.Column('to', sa.Time(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deprtment_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('from', 'to', 'day')
    )
    op.drop_table('departments')
    op.alter_column('patients', 'department',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'patients', 'Users', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'department',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('departments',
    sa.Column('num', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from', mysql.TIME(), nullable=False),
    sa.Column('to', mysql.TIME(), nullable=False),
    sa.Column('day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('num', 'from', 'to', 'day'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('departments_times')
    # ### end Alembic commands ###
