"""empty message

Revision ID: 94f19f9f9b5f
Revises: 96ac93cabd2a
Create Date: 2022-09-16 17:45:40.080728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94f19f9f9b5f'
down_revision = '96ac93cabd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_hour', sa.Time(), nullable=True),
    sa.Column('to_hour', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_times_user_id'), 'users_times', ['user_id'], unique=False)
    op.drop_table('departments_times')
    op.add_column('events', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'Users', ['department_id'], ['id'])
    op.add_column('patients', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patients_department_id'), 'patients', ['department_id'], unique=False)
    op.drop_constraint('patients_ibfk_1', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'Users', ['department_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('patients', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('department', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_ibfk_1', 'patients', 'Users', ['department'], ['id'])
    op.drop_index(op.f('ix_patients_department_id'), table_name='patients')
    op.drop_column('patients', 'department_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'department_id')
    op.create_table('departments_times',
    sa.Column('deprtment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from', mysql.TIME(), nullable=False),
    sa.Column('to', mysql.TIME(), nullable=False),
    sa.Column('day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deprtment_id'], ['Users.id'], name='departments_times_ibfk_1'),
    sa.PrimaryKeyConstraint('from', 'to', 'day'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_users_times_user_id'), table_name='users_times')
    op.drop_table('users_times')
    # ### end Alembic commands ###
