"""change contact_time

Revision ID: 96ac93cabd2a
Revises: da31b6678a8f
Create Date: 2022-09-06 03:03:48.541886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ac93cabd2a'
down_revision = 'da31b6678a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_times', sa.Column('from_hour', sa.Time(), nullable=True))
    op.drop_column('contacts_times', 'from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_times', sa.Column('from', mysql.TIME(), nullable=True))
    op.drop_column('contacts_times', 'from_hour')
    # ### end Alembic commands ###
