"""change contact_time columns

Revision ID: da31b6678a8f
Revises: dcda2806e424
Create Date: 2022-09-06 02:55:59.376141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da31b6678a8f'
down_revision = 'dcda2806e424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_times', sa.Column('to_hour', sa.Time(), nullable=True))
    op.drop_column('contacts_times', 'to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_times', sa.Column('to', mysql.TIME(), nullable=True))
    op.drop_column('contacts_times', 'to_hour')
    # ### end Alembic commands ###
