"""fk contacts times

Revision ID: dc50c465af39
Revises: 1c13336cda69
Create Date: 2022-09-03 17:08:54.265615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc50c465af39'
down_revision = '1c13336cda69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_times',
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('from', sa.Time(), nullable=False),
    sa.Column('to', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'contact_id', 'from', 'to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_times')
    # ### end Alembic commands ###
